INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('1', 'Quận Ba Đình', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('2', 'Quận Hoàn Kiếm', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('3', 'Quận Tây Hồ', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('4', 'Quận Long Biên', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('5', 'Quận Cầu Giấy', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('6', 'Quận Đống Đa', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('7', 'Quận Hai Bà Trưng', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('8', 'Quận Hoàng Mai', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('9', 'Quận Thanh Xuân', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('16', 'Huyện Sóc Sơn', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('17', 'Huyện Đông Anh', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('18', 'Huyện Gia Lâm', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('19', 'Quận Nam Từ Liêm', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('20', 'Huyện Thanh Trì', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('21', 'Quận Bắc Từ Liêm', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('250', 'Huyện Mê Linh', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('268', 'Quận Hà Đông', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('269', 'Thị xã Sơn Tây', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('271', 'Huyện Ba Vì', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('272', 'Huyện Phúc Thọ', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('273', 'Huyện Đan Phượng', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('274', 'Huyện Hoài Đức', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('275', 'Huyện Quốc Oai', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('276', 'Huyện Thạch Thất', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('277', 'Huyện Chương Mỹ', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('278', 'Huyện Thanh Oai', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('279', 'Huyện Thường Tín', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('280', 'Huyện Phú Xuyên', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('281', 'Huyện Ứng Hòa', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('282', 'Huyện Mỹ Đức', '1');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('24', 'Thành phố Hà Giang', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('26', 'Huyện Đồng Văn', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('27', 'Huyện Mèo Vạc', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('28', 'Huyện Yên Minh', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('29', 'Huyện Quản Bạ', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('30', 'Huyện Vị Xuyên', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('31', 'Huyện Bắc Mê', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('32', 'Huyện Hoàng Su Phì', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('33', 'Huyện Xín Mần', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('34', 'Huyện Bắc Quang', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('35', 'Huyện Quang Bình', '2');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('40', 'Thành phố Cao Bằng', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('42', 'Huyện Bảo Lâm', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('43', 'Huyện Bảo Lạc', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('44', 'Huyện Thông Nông', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('45', 'Huyện Hà Quảng', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('46', 'Huyện Trà Lĩnh', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('47', 'Huyện Trùng Khánh', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('48', 'Huyện Hạ Lang', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('49', 'Huyện Quảng Uyên', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('50', 'Huyện Phục Hoà', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('51', 'Huyện Hoà An', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('52', 'Huyện Nguyên Bình', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('53', 'Huyện Thạch An', '4');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('58', 'Thành Phố Bắc Kạn', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('60', 'Huyện Pác Nặm', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('61', 'Huyện Ba Bể', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('62', 'Huyện Ngân Sơn', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('63', 'Huyện Bạch Thông', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('64', 'Huyện Chợ Đồn', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('65', 'Huyện Chợ Mới', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('66', 'Huyện Na Rì', '6');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('70', 'Thành phố Tuyên Quang', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('71', 'Huyện Lâm Bình', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('72', 'Huyện Nà Hang', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('73', 'Huyện Chiêm Hóa', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('74', 'Huyện Hàm Yên', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('75', 'Huyện Yên Sơn', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('76', 'Huyện Sơn Dương', '8');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('80', 'Thành phố Lào Cai', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('82', 'Huyện Bát Xát', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('83', 'Huyện Mường Khương', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('84', 'Huyện Si Ma Cai', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('85', 'Huyện Bắc Hà', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('86', 'Huyện Bảo Thắng', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('87', 'Huyện Bảo Yên', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('88', 'Huyện Sa Pa', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('89', 'Huyện Văn Bàn', '10');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('94', 'Thành phố Điện Biên Phủ', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('95', 'Thị Xã Mường Lay', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('96', 'Huyện Mường Nhé', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('97', 'Huyện Mường Chà', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('98', 'Huyện Tủa Chùa', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('99', 'Huyện Tuần Giáo', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('100', 'Huyện Điện Biên', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('101', 'Huyện Điện Biên Đông', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('102', 'Huyện Mường Ảng', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('103', 'Huyện Nậm Pồ', '11');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('105', 'Thành phố Lai Châu', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('106', 'Huyện Tam Đường', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('107', 'Huyện Mường Tè', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('108', 'Huyện Sìn Hồ', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('109', 'Huyện Phong Thổ', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('110', 'Huyện Than Uyên', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('111', 'Huyện Tân Uyên', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('112', 'Huyện Nậm Nhùn', '12');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('116', 'Thành phố Sơn La', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('118', 'Huyện Quỳnh Nhai', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('119', 'Huyện Thuận Châu', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('120', 'Huyện Mường La', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('121', 'Huyện Bắc Yên', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('122', 'Huyện Phù Yên', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('123', 'Huyện Mộc Châu', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('124', 'Huyện Yên Châu', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('125', 'Huyện Mai Sơn', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('126', 'Huyện Sông Mã', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('127', 'Huyện Sốp Cộp', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('128', 'Huyện Vân Hồ', '14');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('132', 'Thành phố Yên Bái', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('133', 'Thị xã Nghĩa Lộ', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('135', 'Huyện Lục Yên', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('136', 'Huyện Văn Yên', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('137', 'Huyện Mù Căng Chải', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('138', 'Huyện Trấn Yên', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('139', 'Huyện Trạm Tấu', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('140', 'Huyện Văn Chấn', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('141', 'Huyện Yên Bình', '15');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('148', 'Thành phố Hòa Bình', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('150', 'Huyện Đà Bắc', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('151', 'Huyện Kỳ Sơn', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('152', 'Huyện Lương Sơn', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('153', 'Huyện Kim Bôi', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('154', 'Huyện Cao Phong', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('155', 'Huyện Tân Lạc', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('156', 'Huyện Mai Châu', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('157', 'Huyện Lạc Sơn', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('158', 'Huyện Yên Thủy', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('159', 'Huyện Lạc Thủy', '17');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('164', 'Thành phố Thái Nguyên', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('165', 'Thành phố Sông Công', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('167', 'Huyện Định Hóa', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('168', 'Huyện Phú Lương', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('169', 'Huyện Đồng Hỷ', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('170', 'Huyện Võ Nhai', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('171', 'Huyện Đại Từ', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('172', 'Thị xã Phổ Yên', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('173', 'Huyện Phú Bình', '19');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('178', 'Thành phố Lạng Sơn', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('180', 'Huyện Tràng Định', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('181', 'Huyện Bình Gia', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('182', 'Huyện Văn Lãng', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('183', 'Huyện Cao Lộc', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('184', 'Huyện Văn Quan', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('185', 'Huyện Bắc Sơn', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('186', 'Huyện Hữu Lũng', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('187', 'Huyện Chi Lăng', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('188', 'Huyện Lộc Bình', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('189', 'Huyện Đình Lập', '20');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('193', 'Thành phố Hạ Long', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('194', 'Thành phố Móng Cái', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('195', 'Thành phố Cẩm Phả', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('196', 'Thành phố Uông Bí', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('198', 'Huyện Bình Liêu', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('199', 'Huyện Tiên Yên', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('200', 'Huyện Đầm Hà', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('201', 'Huyện Hải Hà', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('202', 'Huyện Ba Chẽ', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('203', 'Huyện Vân Đồn', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('204', 'Huyện Hoành Bồ', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('205', 'Thị xã Đông Triều', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('206', 'Thị xã Quảng Yên', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('207', 'Huyện Cô Tô', '22');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('213', 'Thành phố Bắc Giang', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('215', 'Huyện Yên Thế', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('216', 'Huyện Tân Yên', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('217', 'Huyện Lạng Giang', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('218', 'Huyện Lục Nam', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('219', 'Huyện Lục Ngạn', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('220', 'Huyện Sơn Động', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('221', 'Huyện Yên Dũng', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('222', 'Huyện Việt Yên', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('223', 'Huyện Hiệp Hòa', '24');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('227', 'Thành phố Việt Trì', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('228', 'Thị xã Phú Thọ', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('230', 'Huyện Đoan Hùng', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('231', 'Huyện Hạ Hoà', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('232', 'Huyện Thanh Ba', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('233', 'Huyện Phù Ninh', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('234', 'Huyện Yên Lập', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('235', 'Huyện Cẩm Khê', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('236', 'Huyện Tam Nông', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('237', 'Huyện Lâm Thao', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('238', 'Huyện Thanh Sơn', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('239', 'Huyện Thanh Thuỷ', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('240', 'Huyện Tân Sơn', '25');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('243', 'Thành phố Vĩnh Yên', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('244', 'Thị xã Phúc Yên', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('246', 'Huyện Lập Thạch', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('247', 'Huyện Tam Dương', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('248', 'Huyện Tam Đảo', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('249', 'Huyện Bình Xuyên', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('251', 'Huyện Yên Lạc', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('252', 'Huyện Vĩnh Tường', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('253', 'Huyện Sông Lô', '26');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('256', 'Thành phố Bắc Ninh', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('258', 'Huyện Yên Phong', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('259', 'Huyện Quế Võ', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('260', 'Huyện Tiên Du', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('261', 'Thị xã Từ Sơn', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('262', 'Huyện Thuận Thành', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('263', 'Huyện Gia Bình', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('264', 'Huyện Lương Tài', '27');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('288', 'Thành phố Hải Dương', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('290', 'Thị xã Chí Linh', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('291', 'Huyện Nam Sách', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('292', 'Huyện Kinh Môn', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('293', 'Huyện Kim Thành', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('294', 'Huyện Thanh Hà', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('295', 'Huyện Cẩm Giàng', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('296', 'Huyện Bình Giang', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('297', 'Huyện Gia Lộc', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('298', 'Huyện Tứ Kỳ', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('299', 'Huyện Ninh Giang', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('300', 'Huyện Thanh Miện', '30');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('303', 'Quận Hồng Bàng', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('304', 'Quận Ngô Quyền', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('305', 'Quận Lê Chân', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('306', 'Quận Hải An', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('307', 'Quận Kiến An', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('308', 'Quận Đồ Sơn', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('309', 'Quận Dương Kinh', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('311', 'Huyện Thuỷ Nguyên', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('312', 'Huyện An Dương', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('313', 'Huyện An Lão', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('314', 'Huyện Kiến Thuỵ', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('315', 'Huyện Tiên Lãng', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('316', 'Huyện Vĩnh Bảo', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('317', 'Huyện Cát Hải', '31');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('323', 'Thành phố Hưng Yên', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('325', 'Huyện Văn Lâm', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('326', 'Huyện Văn Giang', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('327', 'Huyện Yên Mỹ', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('328', 'Huyện Mỹ Hào', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('329', 'Huyện Ân Thi', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('330', 'Huyện Khoái Châu', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('331', 'Huyện Kim Động', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('332', 'Huyện Tiên Lữ', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('333', 'Huyện Phù Cừ', '33');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('336', 'Thành phố Thái Bình', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('338', 'Huyện Quỳnh Phụ', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('339', 'Huyện Hưng Hà', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('340', 'Huyện Đông Hưng', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('341', 'Huyện Thái Thụy', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('342', 'Huyện Tiền Hải', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('343', 'Huyện Kiến Xương', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('344', 'Huyện Vũ Thư', '34');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('347', 'Thành phố Phủ Lý', '35');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('349', 'Huyện Duy Tiên', '35');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('350', 'Huyện Kim Bảng', '35');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('351', 'Huyện Thanh Liêm', '35');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('352', 'Huyện Bình Lục', '35');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('353', 'Huyện Lý Nhân', '35');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('356', 'Thành phố Nam Định', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('358', 'Huyện Mỹ Lộc', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('359', 'Huyện Vụ Bản', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('360', 'Huyện Ý Yên', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('361', 'Huyện Nghĩa Hưng', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('362', 'Huyện Nam Trực', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('363', 'Huyện Trực Ninh', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('364', 'Huyện Xuân Trường', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('365', 'Huyện Giao Thủy', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('366', 'Huyện Hải Hậu', '36');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('369', 'Thành phố Ninh Bình', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('370', 'Thành phố Tam Điệp', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('372', 'Huyện Nho Quan', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('373', 'Huyện Gia Viễn', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('374', 'Huyện Hoa Lư', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('375', 'Huyện Yên Khánh', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('376', 'Huyện Kim Sơn', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('377', 'Huyện Yên Mô', '37');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('380', 'Thành phố Thanh Hóa', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('381', 'Thị xã Bỉm Sơn', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('382', 'Thành phố Sầm Sơn', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('384', 'Huyện Mường Lát', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('385', 'Huyện Quan Hóa', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('386', 'Huyện Bá Thước', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('387', 'Huyện Quan Sơn', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('388', 'Huyện Lang Chánh', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('389', 'Huyện Ngọc Lặc', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('390', 'Huyện Cẩm Thủy', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('391', 'Huyện Thạch Thành', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('392', 'Huyện Hà Trung', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('393', 'Huyện Vĩnh Lộc', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('394', 'Huyện Yên Định', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('395', 'Huyện Thọ Xuân', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('396', 'Huyện Thường Xuân', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('397', 'Huyện Triệu Sơn', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('398', 'Huyện Thiệu Hóa', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('399', 'Huyện Hoằng Hóa', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('400', 'Huyện Hậu Lộc', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('401', 'Huyện Nga Sơn', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('402', 'Huyện Như Xuân', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('403', 'Huyện Như Thanh', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('404', 'Huyện Nông Cống', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('405', 'Huyện Đông Sơn', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('406', 'Huyện Quảng Xương', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('407', 'Huyện Tĩnh Gia', '38');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('412', 'Thành phố Vinh', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('413', 'Thị xã Cửa Lò', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('414', 'Thị xã Thái Hoà', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('415', 'Huyện Quế Phong', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('416', 'Huyện Quỳ Châu', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('418', 'Huyện Tương Dương', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('419', 'Huyện Nghĩa Đàn', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('420', 'Huyện Quỳ Hợp', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('421', 'Huyện Quỳnh Lưu', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('422', 'Huyện Con Cuông', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('423', 'Huyện Tân Kỳ', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('424', 'Huyện Anh Sơn', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('425', 'Huyện Diễn Châu', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('426', 'Huyện Yên Thành', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('427', 'Huyện Đô Lương', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('428', 'Huyện Thanh Chương', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('429', 'Huyện Nghi Lộc', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('430', 'Huyện Nam Đàn', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('431', 'Huyện Hưng Nguyên', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('432', 'Thị xã Hoàng Mai', '40');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('436', 'Thành phố Hà Tĩnh', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('437', 'Thị xã Hồng Lĩnh', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('439', 'Huyện Hương Sơn', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('440', 'Huyện Đức Thọ', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('441', 'Huyện Vũ Quang', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('442', 'Huyện Nghi Xuân', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('443', 'Huyện Can Lộc', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('444', 'Huyện Hương Khê', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('445', 'Huyện Thạch Hà', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('446', 'Huyện Cẩm Xuyên', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('447', 'Huyện Kỳ Anh', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('448', 'Huyện Lộc Hà', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('449', 'Thị xã Kỳ Anh', '42');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('450', 'Thành Phố Đồng Hới', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('452', 'Huyện Minh Hóa', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('453', 'Huyện Tuyên Hóa', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('454', 'Huyện Quảng Trạch', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('455', 'Huyện Bố Trạch', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('456', 'Huyện Quảng Ninh', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('457', 'Huyện Lệ Thủy', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('458', 'Thị xã Ba Đồn', '44');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('461', 'Thành phố Đông Hà', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('462', 'Thị xã Quảng Trị', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('464', 'Huyện Vĩnh Linh', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('465', 'Huyện Hướng Hóa', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('466', 'Huyện Gio Linh', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('467', 'Huyện Đa Krông', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('468', 'Huyện Cam Lộ', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('469', 'Huyện Triệu Phong', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('470', 'Huyện Hải Lăng', '45');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('474', 'Thành phố Huế', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('476', 'Huyện Phong Điền', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('477', 'Huyện Quảng Điền', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('478', 'Huyện Phú Vang', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('479', 'Thị xã Hương Thủy', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('480', 'Thị xã Hương Trà', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('481', 'Huyện A Lưới', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('482', 'Huyện Phú Lộc', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('483', 'Huyện Nam Đông', '46');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('490', 'Quận Liên Chiểu', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('491', 'Quận Thanh Khê', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('492', 'Quận Hải Châu', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('493', 'Quận Sơn Trà', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('494', 'Quận Ngũ Hành Sơn', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('495', 'Quận Cẩm Lệ', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('497', 'Huyện Hòa Vang', '48');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('502', 'Thành phố Tam Kỳ', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('503', 'Thành phố Hội An', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('504', 'Huyện Tây Giang', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('505', 'Huyện Đông Giang', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('506', 'Huyện Đại Lộc', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('507', 'Thị xã Điện Bàn', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('508', 'Huyện Duy Xuyên', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('509', 'Huyện Quế Sơn', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('510', 'Huyện Nam Giang', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('511', 'Huyện Phước Sơn', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('512', 'Huyện Hiệp Đức', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('513', 'Huyện Thăng Bình', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('514', 'Huyện Tiên Phước', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('515', 'Huyện Bắc Trà My', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('516', 'Huyện Nam Trà My', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('517', 'Huyện Núi Thành', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('518', 'Huyện Phú Ninh', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('519', 'Huyện Nông Sơn', '49');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('522', 'Thành phố Quảng Ngãi', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('524', 'Huyện Bình Sơn', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('525', 'Huyện Trà Bồng', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('526', 'Huyện Tây Trà', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('527', 'Huyện Sơn Tịnh', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('528', 'Huyện Tư Nghĩa', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('529', 'Huyện Sơn Hà', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('530', 'Huyện Sơn Tây', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('531', 'Huyện Minh Long', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('532', 'Huyện Nghĩa Hành', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('533', 'Huyện Mộ Đức', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('534', 'Huyện Đức Phổ', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('535', 'Huyện Ba Tơ', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('536', 'Huyện Lý Sơn', '51');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('540', 'Thành phố Qui Nhơn', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('543', 'Huyện Hoài Nhơn', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('544', 'Huyện Hoài Ân', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('545', 'Huyện Phù Mỹ', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('546', 'Huyện Vĩnh Thạnh', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('547', 'Huyện Tây Sơn', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('548', 'Huyện Phù Cát', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('549', 'Thị xã An Nhơn', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('550', 'Huyện Tuy Phước', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('551', 'Huyện Vân Canh', '52');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('555', 'Thành phố Tuy Hoà', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('557', 'Thị xã Sông Cầu', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('558', 'Huyện Đồng Xuân', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('559', 'Huyện Tuy An', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('560', 'Huyện Sơn Hòa', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('561', 'Huyện Sông Hinh', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('562', 'Huyện Tây Hoà', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('563', 'Huyện Phú Hoà', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('564', 'Huyện Đông Hòa', '54');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('568', 'Thành phố Nha Trang', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('569', 'Thành phố Cam Ranh', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('570', 'Huyện Cam Lâm', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('571', 'Huyện Vạn Ninh', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('572', 'Thị xã Ninh Hòa', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('573', 'Huyện Khánh Vĩnh', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('574', 'Huyện Diên Khánh', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('575', 'Huyện Khánh Sơn', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('576', 'Huyện Trường Sa', '56');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('582', 'Thành phố Phan Rang-Tháp Chàm', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('584', 'Huyện Bác Ái', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('585', 'Huyện Ninh Sơn', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('586', 'Huyện Ninh Hải', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('587', 'Huyện Ninh Phước', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('588', 'Huyện Thuận Bắc', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('589', 'Huyện Thuận Nam', '58');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('593', 'Thành phố Phan Thiết', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('594', 'Thị xã La Gi', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('595', 'Huyện Tuy Phong', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('596', 'Huyện Bắc Bình', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('597', 'Huyện Hàm Thuận Bắc', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('598', 'Huyện Hàm Thuận Nam', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('599', 'Huyện Tánh Linh', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('600', 'Huyện Đức Linh', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('601', 'Huyện Hàm Tân', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('602', 'Huyện Phú Quí', '60');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('608', 'Thành phố Kon Tum', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('610', 'Huyện Đắk Glei', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('611', 'Huyện Ngọc Hồi', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('612', 'Huyện Đắk Tô', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('613', 'Huyện Kon Plông', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('614', 'Huyện Kon Rẫy', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('615', 'Huyện Đắk Hà', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('616', 'Huyện Sa Thầy', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('617', 'Huyện Tu Mơ Rông', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('618', 'Huyện Ia H'' Drai', '62');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('622', 'Thành phố Pleiku', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('623', 'Thị xã An Khê', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('624', 'Thị xã Ayun Pa', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('625', 'Huyện KBang', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('626', 'Huyện Đăk Đoa', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('627', 'Huyện Chư Păh', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('628', 'Huyện Ia Grai', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('629', 'Huyện Mang Yang', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('630', 'Huyện Kông Chro', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('631', 'Huyện Đức Cơ', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('632', 'Huyện Chư Prông', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('633', 'Huyện Chư Sê', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('634', 'Huyện Đăk Pơ', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('635', 'Huyện Ia Pa', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('637', 'Huyện Krông Pa', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('638', 'Huyện Phú Thiện', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('639', 'Huyện Chư Pưh', '64');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('643', 'Thành phố Buôn Ma Thuột', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('644', 'Thị Xã Buôn Hồ', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('645', 'Huyện Ea H''leo', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('646', 'Huyện Ea Súp', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('647', 'Huyện Buôn Đôn', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('648', 'Huyện Cư M''gar', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('649', 'Huyện Krông Búk', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('650', 'Huyện Krông Năng', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('651', 'Huyện Ea Kar', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('652', 'Huyện M''Đrắk', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('653', 'Huyện Krông Bông', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('654', 'Huyện Krông Pắc', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('655', 'Huyện Krông A Na', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('656', 'Huyện Lắk', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('657', 'Huyện Cư Kuin', '66');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('660', 'Thị xã Gia Nghĩa', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('661', 'Huyện Đăk Glong', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('662', 'Huyện Cư Jút', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('663', 'Huyện Đắk Mil', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('664', 'Huyện Krông Nô', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('665', 'Huyện Đắk Song', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('666', 'Huyện Đắk R''Lấp', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('667', 'Huyện Tuy Đức', '67');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('672', 'Thành phố Đà Lạt', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('673', 'Thành phố Bảo Lộc', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('674', 'Huyện Đam Rông', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('675', 'Huyện Lạc Dương', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('676', 'Huyện Lâm Hà', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('677', 'Huyện Đơn Dương', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('678', 'Huyện Đức Trọng', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('679', 'Huyện Di Linh', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('681', 'Huyện Đạ Huoai', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('682', 'Huyện Đạ Tẻh', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('683', 'Huyện Cát Tiên', '68');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('688', 'Thị xã Phước Long', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('689', 'Thị xã Đồng Xoài', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('690', 'Thị xã Bình Long', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('691', 'Huyện Bù Gia Mập', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('692', 'Huyện Lộc Ninh', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('693', 'Huyện Bù Đốp', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('694', 'Huyện Hớn Quản', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('695', 'Huyện Đồng Phú', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('696', 'Huyện Bù Đăng', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('697', 'Huyện Chơn Thành', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('698', 'Huyện Phú Riềng', '70');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('703', 'Thành phố Tây Ninh', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('705', 'Huyện Tân Biên', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('706', 'Huyện Tân Châu', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('707', 'Huyện Dương Minh Châu', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('708', 'Huyện Châu Thành', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('709', 'Huyện Hòa Thành', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('710', 'Huyện Gò Dầu', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('711', 'Huyện Bến Cầu', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('712', 'Huyện Trảng Bàng', '72');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('718', 'Thành phố Thủ Dầu Một', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('719', 'Huyện Bàu Bàng', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('720', 'Huyện Dầu Tiếng', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('721', 'Thị xã Bến Cát', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('722', 'Huyện Phú Giáo', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('723', 'Thị xã Tân Uyên', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('724', 'Thị xã Dĩ An', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('725', 'Thị xã Thuận An', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('726', 'Huyện Bắc Tân Uyên', '74');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('731', 'Thành phố Biên Hòa', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('732', 'Thị xã Long Khánh', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('734', 'Huyện Tân Phú', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('735', 'Huyện Vĩnh Cửu', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('736', 'Huyện Định Quán', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('737', 'Huyện Trảng Bom', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('738', 'Huyện Thống Nhất', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('739', 'Huyện Cẩm Mỹ', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('740', 'Huyện Long Thành', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('741', 'Huyện Xuân Lộc', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('742', 'Huyện Nhơn Trạch', '75');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('747', 'Thành phố Vũng Tàu', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('748', 'Thành phố Bà Rịa', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('750', 'Huyện Châu Đức', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('751', 'Huyện Xuyên Mộc', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('752', 'Huyện Long Điền', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('753', 'Huyện Đất Đỏ', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('754', 'Huyện Tân Thành', '77');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('760', 'Quận 1', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('761', 'Quận 12', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('762', 'Quận Thủ Đức', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('763', 'Quận 9', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('764', 'Quận Gò Vấp', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('765', 'Quận Bình Thạnh', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('766', 'Quận Tân Bình', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('767', 'Quận Tân Phú', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('768', 'Quận Phú Nhuận', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('769', 'Quận 2', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('770', 'Quận 3', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('771', 'Quận 10', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('772', 'Quận 11', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('773', 'Quận 4', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('774', 'Quận 5', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('775', 'Quận 6', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('776', 'Quận 8', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('777', 'Quận Bình Tân', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('778', 'Quận 7', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('783', 'Huyện Củ Chi', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('784', 'Huyện Hóc Môn', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('785', 'Huyện Bình Chánh', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('786', 'Huyện Nhà Bè', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('787', 'Huyện Cần Giờ', '79');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('794', 'Thành phố Tân An', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('795', 'Thị xã Kiến Tường', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('796', 'Huyện Tân Hưng', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('797', 'Huyện Vĩnh Hưng', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('798', 'Huyện Mộc Hóa', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('799', 'Huyện Tân Thạnh', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('800', 'Huyện Thạnh Hóa', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('801', 'Huyện Đức Huệ', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('802', 'Huyện Đức Hòa', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('803', 'Huyện Bến Lức', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('804', 'Huyện Thủ Thừa', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('805', 'Huyện Tân Trụ', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('806', 'Huyện Cần Đước', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('807', 'Huyện Cần Giuộc', '80');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('815', 'Thành phố Mỹ Tho', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('816', 'Thị xã Gò Công', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('817', 'Thị xã Cai Lậy', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('818', 'Huyện Tân Phước', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('819', 'Huyện Cái Bè', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('820', 'Huyện Cai Lậy', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('822', 'Huyện Chợ Gạo', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('823', 'Huyện Gò Công Tây', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('824', 'Huyện Gò Công Đông', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('825', 'Huyện Tân Phú Đông', '82');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('829', 'Thành phố Bến Tre', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('832', 'Huyện Chợ Lách', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('833', 'Huyện Mỏ Cày Nam', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('834', 'Huyện Giồng Trôm', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('835', 'Huyện Bình Đại', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('836', 'Huyện Ba Tri', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('837', 'Huyện Thạnh Phú', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('838', 'Huyện Mỏ Cày Bắc', '83');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('842', 'Thành phố Trà Vinh', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('844', 'Huyện Càng Long', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('845', 'Huyện Cầu Kè', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('846', 'Huyện Tiểu Cần', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('848', 'Huyện Cầu Ngang', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('849', 'Huyện Trà Cú', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('850', 'Huyện Duyên Hải', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('851', 'Thị xã Duyên Hải', '84');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('855', 'Thành phố Vĩnh Long', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('857', 'Huyện Long Hồ', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('858', 'Huyện Mang Thít', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('859', 'Huyện Vũng Liêm', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('860', 'Huyện Tam Bình', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('861', 'Thị xã Bình Minh', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('862', 'Huyện Trà Ôn', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('863', 'Huyện Bình Tân', '86');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('866', 'Thành phố Cao Lãnh', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('867', 'Thành phố Sa Đéc', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('868', 'Thị xã Hồng Ngự', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('869', 'Huyện Tân Hồng', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('870', 'Huyện Hồng Ngự', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('872', 'Huyện Tháp Mười', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('873', 'Huyện Cao Lãnh', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('874', 'Huyện Thanh Bình', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('875', 'Huyện Lấp Vò', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('876', 'Huyện Lai Vung', '87');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('883', 'Thành phố Long Xuyên', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('884', 'Thành phố Châu Đốc', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('886', 'Huyện An Phú', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('887', 'Thị xã Tân Châu', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('888', 'Huyện Phú Tân', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('889', 'Huyện Châu Phú', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('890', 'Huyện Tịnh Biên', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('891', 'Huyện Tri Tôn', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('894', 'Huyện Thoại Sơn', '89');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('899', 'Thành phố Rạch Giá', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('900', 'Thị xã Hà Tiên', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('902', 'Huyện Kiên Lương', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('903', 'Huyện Hòn Đất', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('904', 'Huyện Tân Hiệp', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('906', 'Huyện Giồng Riềng', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('907', 'Huyện Gò Quao', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('908', 'Huyện An Biên', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('909', 'Huyện An Minh', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('910', 'Huyện Vĩnh Thuận', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('911', 'Huyện Phú Quốc', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('912', 'Huyện Kiên Hải', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('913', 'Huyện U Minh Thượng', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('914', 'Huyện Giang Thành', '91');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('916', 'Quận Ninh Kiều', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('917', 'Quận Ô Môn', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('918', 'Quận Bình Thuỷ', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('919', 'Quận Cái Răng', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('923', 'Quận Thốt Nốt', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('925', 'Huyện Cờ Đỏ', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('927', 'Huyện Thới Lai', '92');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('930', 'Thành phố Vị Thanh', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('931', 'Thị xã Ngã Bảy', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('932', 'Huyện Châu Thành A', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('934', 'Huyện Phụng Hiệp', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('935', 'Huyện Vị Thuỷ', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('936', 'Huyện Long Mỹ', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('937', 'Thị xã Long Mỹ', '93');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('941', 'Thành phố Sóc Trăng', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('943', 'Huyện Kế Sách', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('944', 'Huyện Mỹ Tú', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('945', 'Huyện Cù Lao Dung', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('946', 'Huyện Long Phú', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('947', 'Huyện Mỹ Xuyên', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('948', 'Thị xã Ngã Năm', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('949', 'Huyện Thạnh Trị', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('950', 'Thị xã Vĩnh Châu', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('951', 'Huyện Trần Đề', '94');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('954', 'Thành phố Bạc Liêu', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('956', 'Huyện Hồng Dân', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('957', 'Huyện Phước Long', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('958', 'Huyện Vĩnh Lợi', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('959', 'Thị xã Giá Rai', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('960', 'Huyện Đông Hải', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('961', 'Huyện Hoà Bình', '95');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('964', 'Thành phố Cà Mau', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('966', 'Huyện U Minh', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('967', 'Huyện Thới Bình', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('968', 'Huyện Trần Văn Thời', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('969', 'Huyện Cái Nước', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('970', 'Huyện Đầm Dơi', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('971', 'Huyện Năm Căn', '96');
INSERT INTO `cities` (`id`, `name`, `province_id`) VALUES ('973', 'Huyện Ngọc Hiển', '96');