INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('1', 'AFGHANISTAN', 'AF', 'AFG', '4', '93', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('2', 'ALBANIA', 'AL', 'ALB', '8', '355', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('3', 'ALGERIA', 'DZ', 'DZA', '12', '213', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('4', 'AMERICAN SAMOA', 'AS', 'ASM', '16', '1684', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('5', 'ANDORRA', 'AD', 'AND', '20', '376', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('6', 'ANGOLA', 'AO', 'AGO', '24', '244', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('7', 'ANGUILLA', 'AI', 'AIA', '660', '1264', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('8', 'ANTARCTICA', 'AQ', 'NULL', 'NULL', '0', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('9', 'ANTIGUA AND BARBUDA', 'AG', 'ATG', '28', '1268', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('10', 'ARGENTINA', 'AR', 'ARG', '32', '54', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('11', 'ARMENIA', 'AM', 'ARM', '51', '374', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('12', 'ARUBA', 'AW', 'ABW', '533', '297', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('13', 'AUSTRALIA', 'AU', 'AUS', '36', '61', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('14', 'AUSTRIA', 'AT', 'AUT', '40', '43', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('15', 'AZERBAIJAN', 'AZ', 'AZE', '31', '994', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('16', 'BAHAMAS', 'BS', 'BHS', '44', '1242', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('17', 'BAHRAIN', 'BH', 'BHR', '48', '973', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('18', 'BANGLADESH', 'BD', 'BGD', '50', '880', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('19', 'BARBADOS', 'BB', 'BRB', '52', '1246', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('20', 'BELARUS', 'BY', 'BLR', '112', '375', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('21', 'BELGIUM', 'BE', 'BEL', '56', '32', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('22', 'BELIZE', 'BZ', 'BLZ', '84', '501', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('23', 'BENIN', 'BJ', 'BEN', '204', '229', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('24', 'BERMUDA', 'BM', 'BMU', '60', '1441', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('25', 'BHUTAN', 'BT', 'BTN', '64', '975', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('26', 'BOLIVIA', 'BO', 'BOL', '68', '591', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('27', 'BOSNIA AND HERZEGOVINA', 'BA', 'BIH', '70', '387', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('28', 'BOTSWANA', 'BW', 'BWA', '72', '267', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('29', 'BOUVET ISLAND', 'BV', 'NULL', 'NULL', '0', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('30', 'BRAZIL', 'BR', 'BRA', '76', '55', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('31', 'BRITISH INDIAN OCEAN TERRITORY', 'IO', 'NULL', 'NULL', '246', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('32', 'BRUNEI DARUSSALAM', 'BN', 'BRN', '96', '673', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('33', 'BULGARIA', 'BG', 'BGR', '100', '359', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('34', 'BURKINA FASO', 'BF', 'BFA', '854', '226', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('35', 'BURUNDI', 'BI', 'BDI', '108', '257', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('36', 'CAMBODIA', 'KH', 'KHM', '116', '855', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('37', 'CAMEROON', 'CM', 'CMR', '120', '237', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('38', 'CANADA', 'CA', 'CAN', '124', '1', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('39', 'CAPE VERDE', 'CV', 'CPV', '132', '238', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('40', 'CAYMAN ISLANDS', 'KY', 'CYM', '136', '1345', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('41', 'CENTRAL AFRICAN REPUBLIC', 'CF', 'CAF', '140', '236', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('42', 'CHAD', 'TD', 'TCD', '148', '235', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('43', 'CHILE', 'CL', 'CHL', '152', '56', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('44', 'CHINA', 'CN', 'CHN', '156', '86', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('45', 'CHRISTMAS ISLAND', 'CX', 'NULL', 'NULL', '61', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('46', 'COCOS (KEELING) ISLANDS', 'CC', 'NULL', 'NULL', '672', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('47', 'COLOMBIA', 'CO', 'COL', '170', '57', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('48', 'COMOROS', 'KM', 'COM', '174', '269', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('49', 'CONGO', 'CG', 'COG', '178', '242', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('50', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CD', 'COD', '180', '242', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('51', 'COOK ISLANDS', 'CK', 'COK', '184', '682', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('52', 'COSTA RICA', 'CR', 'CRI', '188', '506', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('53', 'COTE D''IVOIRE', 'CI', 'CIV', '384', '225', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('54', 'CROATIA', 'HR', 'HRV', '191', '385', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('55', 'CUBA', 'CU', 'CUB', '192', '53', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('56', 'CYPRUS', 'CY', 'CYP', '196', '357', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('57', 'CZECH REPUBLIC', 'CZ', 'CZE', '203', '420', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('58', 'DENMARK', 'DK', 'DNK', '208', '45', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('59', 'DJIBOUTI', 'DJ', 'DJI', '262', '253', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('60', 'DOMINICA', 'DM', 'DMA', '212', '1767', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('61', 'DOMINICAN REPUBLIC', 'DO', 'DOM', '214', '1809', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('62', 'ECUADOR', 'EC', 'ECU', '218', '593', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('63', 'EGYPT', 'EG', 'EGY', '818', '20', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('64', 'EL SALVADOR', 'SV', 'SLV', '222', '503', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('65', 'EQUATORIAL GUINEA', 'GQ', 'GNQ', '226', '240', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('66', 'ERITREA', 'ER', 'ERI', '232', '291', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('67', 'ESTONIA', 'EE', 'EST', '233', '372', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('68', 'ETHIOPIA', 'ET', 'ETH', '231', '251', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('69', 'FALKLAND ISLANDS (MALVINAS)', 'FK', 'FLK', '238', '500', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('70', 'FAROE ISLANDS', 'FO', 'FRO', '234', '298', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('71', 'FIJI', 'FJ', 'FJI', '242', '679', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('72', 'FINLAND', 'FI', 'FIN', '246', '358', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('73', 'FRANCE', 'FR', 'FRA', '250', '33', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('74', 'FRENCH GUIANA', 'GF', 'GUF', '254', '594', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('75', 'FRENCH POLYNESIA', 'PF', 'PYF', '258', '689', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('76', 'FRENCH SOUTHERN TERRITORIES', 'TF', 'NULL', 'NULL', '0', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('77', 'GABON', 'GA', 'GAB', '266', '241', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('78', 'GAMBIA', 'GM', 'GMB', '270', '220', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('79', 'GEORGIA', 'GE', 'GEO', '268', '995', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('80', 'GERMANY', 'DE', 'DEU', '276', '49', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('81', 'GHANA', 'GH', 'GHA', '288', '233', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('82', 'GIBRALTAR', 'GI', 'GIB', '292', '350', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('83', 'GREECE', 'GR', 'GRC', '300', '30', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('84', 'GREENLAND', 'GL', 'GRL', '304', '299', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('85', 'GRENADA', 'GD', 'GRD', '308', '1473', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('86', 'GUADELOUPE', 'GP', 'GLP', '312', '590', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('87', 'GUAM', 'GU', 'GUM', '316', '1671', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('88', 'GUATEMALA', 'GT', 'GTM', '320', '502', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('89', 'GUINEA', 'GN', 'GIN', '324', '224', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('90', 'GUINEA-BISSAU', 'GW', 'GNB', '624', '245', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('91', 'GUYANA', 'GY', 'GUY', '328', '592', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('92', 'HAITI', 'HT', 'HTI', '332', '509', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('93', 'HEARD ISLAND AND MCDONALD ISLANDS', 'HM', 'NULL', 'NULL', '0', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('94', 'HOLY SEE (VATICAN CITY STATE)', 'VA', 'VAT', '336', '39', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('95', 'HONDURAS', 'HN', 'HND', '340', '504', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('96', 'HONG KONG', 'HK', 'HKG', '344', '852', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('97', 'HUNGARY', 'HU', 'HUN', '348', '36', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('98', 'ICELAND', 'IS', 'ISL', '352', '354', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('99', 'INDIA', 'IN', 'IND', '356', '91', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('100', 'INDONESIA', 'ID', 'IDN', '360', '62', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('101', 'IRAN, ISLAMIC REPUBLIC OF', 'IR', 'IRN', '364', '98', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('102', 'IRAQ', 'IQ', 'IRQ', '368', '964', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('103', 'IRELAND', 'IE', 'IRL', '372', '353', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('104', 'ISRAEL', 'IL', 'ISR', '376', '972', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('105', 'ITALY', 'IT', 'ITA', '380', '39', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('106', 'JAMAICA', 'JM', 'JAM', '388', '1876', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('107', 'JAPAN', 'JP', 'JPN', '392', '81', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('108', 'JORDAN', 'JO', 'JOR', '400', '962', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('109', 'KAZAKHSTAN', 'KZ', 'KAZ', '398', '7', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('110', 'KENYA', 'KE', 'KEN', '404', '254', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('111', 'KIRIBATI', 'KI', 'KIR', '296', '686', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('112', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'KP', 'PRK', '408', '850', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('113', 'KOREA, REPUBLIC OF', 'KR', 'KOR', '410', '82', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('114', 'KUWAIT', 'KW', 'KWT', '414', '965', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('115', 'KYRGYZSTAN', 'KG', 'KGZ', '417', '996', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('116', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'LA', 'LAO', '418', '856', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('117', 'LATVIA', 'LV', 'LVA', '428', '371', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('118', 'LEBANON', 'LB', 'LBN', '422', '961', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('119', 'LESOTHO', 'LS', 'LSO', '426', '266', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('120', 'LIBERIA', 'LR', 'LBR', '430', '231', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('121', 'LIBYAN ARAB JAMAHIRIYA', 'LY', 'LBY', '434', '218', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('122', 'LIECHTENSTEIN', 'LI', 'LIE', '438', '423', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('123', 'LITHUANIA', 'LT', 'LTU', '440', '370', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('124', 'LUXEMBOURG', 'LU', 'LUX', '442', '352', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('125', 'MACAO', 'MO', 'MAC', '446', '853', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('126', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK', 'MKD', '807', '389', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('127', 'MADAGASCAR', 'MG', 'MDG', '450', '261', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('128', 'MALAWI', 'MW', 'MWI', '454', '265', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('129', 'MALAYSIA', 'MY', 'MYS', '458', '60', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('130', 'MALDIVES', 'MV', 'MDV', '462', '960', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('131', 'MALI', 'ML', 'MLI', '466', '223', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('132', 'MALTA', 'MT', 'MLT', '470', '356', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('133', 'MARSHALL ISLANDS', 'MH', 'MHL', '584', '692', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('134', 'MARTINIQUE', 'MQ', 'MTQ', '474', '596', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('135', 'MAURITANIA', 'MR', 'MRT', '478', '222', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('136', 'MAURITIUS', 'MU', 'MUS', '480', '230', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('137', 'MAYOTTE', 'YT', 'NULL', 'NULL', '269', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('138', 'MEXICO', 'MX', 'MEX', '484', '52', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('139', 'MICRONESIA, FEDERATED STATES OF', 'FM', 'FSM', '583', '691', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('140', 'MOLDOVA, REPUBLIC OF', 'MD', 'MDA', '498', '373', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('141', 'MONACO', 'MC', 'MCO', '492', '377', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('142', 'MONGOLIA', 'MN', 'MNG', '496', '976', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('143', 'MONTSERRAT', 'MS', 'MSR', '500', '1664', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('144', 'MOROCCO', 'MA', 'MAR', '504', '212', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('145', 'MOZAMBIQUE', 'MZ', 'MOZ', '508', '258', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('146', 'MYANMAR', 'MM', 'MMR', '104', '95', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('147', 'NAMIBIA', 'NA', 'NAM', '516', '264', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('148', 'NAURU', 'NR', 'NRU', '520', '674', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('149', 'NEPAL', 'NP', 'NPL', '524', '977', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('150', 'NETHERLANDS', 'NL', 'NLD', '528', '31', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('151', 'NETHERLANDS ANTILLES', 'AN', 'ANT', '530', '599', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('152', 'NEW CALEDONIA', 'NC', 'NCL', '540', '687', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('153', 'NEW ZEALAND', 'NZ', 'NZL', '554', '64', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('154', 'NICARAGUA', 'NI', 'NIC', '558', '505', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('155', 'NIGER', 'NE', 'NER', '562', '227', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('156', 'NIGERIA', 'NG', 'NGA', '566', '234', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('157', 'NIUE', 'NU', 'NIU', '570', '683', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('158', 'NORFOLK ISLAND', 'NF', 'NFK', '574', '672', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('159', 'NORTHERN MARIANA ISLANDS', 'MP', 'MNP', '580', '1670', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('160', 'NORWAY', 'NO', 'NOR', '578', '47', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('161', 'OMAN', 'OM', 'OMN', '512', '968', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('162', 'PAKISTAN', 'PK', 'PAK', '586', '92', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('163', 'PALAU', 'PW', 'PLW', '585', '680', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('164', 'PALESTINIAN TERRITORY, OCCUPIED', 'PS', 'NULL', 'NULL', '970', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('165', 'PANAMA', 'PA', 'PAN', '591', '507', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('166', 'PAPUA NEW GUINEA', 'PG', 'PNG', '598', '675', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('167', 'PARAGUAY', 'PY', 'PRY', '600', '595', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('168', 'PERU', 'PE', 'PER', '604', '51', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('169', 'PHILIPPINES', 'PH', 'PHL', '608', '63', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('170', 'PITCAIRN', 'PN', 'PCN', '612', '0', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('171', 'POLAND', 'PL', 'POL', '616', '48', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('172', 'PORTUGAL', 'PT', 'PRT', '620', '351', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('173', 'PUERTO RICO', 'PR', 'PRI', '630', '1787', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('174', 'QATAR', 'QA', 'QAT', '634', '974', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('175', 'REUNION', 'RE', 'REU', '638', '262', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('176', 'ROMANIA', 'RO', 'ROM', '642', '40', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('177', 'RUSSIAN FEDERATION', 'RU', 'RUS', '643', '70', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('178', 'RWANDA', 'RW', 'RWA', '646', '250', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('179', 'SAINT HELENA', 'SH', 'SHN', '654', '290', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('180', 'SAINT KITTS AND NEVIS', 'KN', 'KNA', '659', '1869', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('181', 'SAINT LUCIA', 'LC', 'LCA', '662', '1758', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('182', 'SAINT PIERRE AND MIQUELON', 'PM', 'SPM', '666', '508', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('183', 'SAINT VINCENT AND THE GRENADINES', 'VC', 'VCT', '670', '1784', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('184', 'SAMOA', 'WS', 'WSM', '882', '684', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('185', 'SAN MARINO', 'SM', 'SMR', '674', '378', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('186', 'SAO TOME AND PRINCIPE', 'ST', 'STP', '678', '239', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('187', 'SAUDI ARABIA', 'SA', 'SAU', '682', '966', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('188', 'SENEGAL', 'SN', 'SEN', '686', '221', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('189', 'SERBIA AND MONTENEGRO', 'CS', 'NULL', 'NULL', '381', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('190', 'SEYCHELLES', 'SC', 'SYC', '690', '248', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('191', 'SIERRA LEONE', 'SL', 'SLE', '694', '232', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('192', 'SINGAPORE', 'SG', 'SGP', '702', '65', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('193', 'SLOVAKIA', 'SK', 'SVK', '703', '421', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('194', 'SLOVENIA', 'SI', 'SVN', '705', '386', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('195', 'SOLOMON ISLANDS', 'SB', 'SLB', '90', '677', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('196', 'SOMALIA', 'SO', 'SOM', '706', '252', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('197', 'SOUTH AFRICA', 'ZA', 'ZAF', '710', '27', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('198', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS', 'NULL', 'NULL', '0', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('199', 'SPAIN', 'ES', 'ESP', '724', '34', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('200', 'SRI LANKA', 'LK', 'LKA', '144', '94', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('201', 'SUDAN', 'SD', 'SDN', '736', '249', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('202', 'SURINAME', 'SR', 'SUR', '740', '597', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('203', 'SVALBARD AND JAN MAYEN', 'SJ', 'SJM', '744', '47', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('204', 'SWAZILAND', 'SZ', 'SWZ', '748', '268', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('205', 'SWEDEN', 'SE', 'SWE', '752', '46', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('206', 'SWITZERLAND', 'CH', 'CHE', '756', '41', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('207', 'SYRIAN ARAB REPUBLIC', 'SY', 'SYR', '760', '963', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('208', 'TAIWAN, PROVINCE OF CHINA', 'TW', 'TWN', '158', '886', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('209', 'TAJIKISTAN', 'TJ', 'TJK', '762', '992', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('210', 'TANZANIA, UNITED REPUBLIC OF', 'TZ', 'TZA', '834', '255', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('211', 'THAILAND', 'TH', 'THA', '764', '66', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('212', 'TIMOR-LESTE', 'TL', 'NULL', 'NULL', '670', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('213', 'TOGO', 'TG', 'TGO', '768', '228', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('214', 'TOKELAU', 'TK', 'TKL', '772', '690', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('215', 'TONGA', 'TO', 'TON', '776', '676', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('216', 'TRINIDAD AND TOBAGO', 'TT', 'TTO', '780', '1868', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('217', 'TUNISIA', 'TN', 'TUN', '788', '216', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('218', 'TURKEY', 'TR', 'TUR', '792', '90', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('219', 'TURKMENISTAN', 'TM', 'TKM', '795', '7370', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('220', 'TURKS AND CAICOS ISLANDS', 'TC', 'TCA', '796', '1649', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('221', 'TUVALU', 'TV', 'TUV', '798', '688', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('222', 'UGANDA', 'UG', 'UGA', '800', '256', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('223', 'UKRAINE', 'UA', 'UKR', '804', '380', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('224', 'UNITED ARAB EMIRATES', 'AE', 'ARE', '784', '971', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('225', 'UNITED KINGDOM', 'GB', 'GBR', '826', '44', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('226', 'UNITED STATES', 'US', 'USA', '840', '1', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('227', 'UNITED STATES MINOR OUTLYING ISLANDS', 'UM', 'NULL', 'NULL', '1', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('228', 'URUGUAY', 'UY', 'URY', '858', '598', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('229', 'UZBEKISTAN', 'UZ', 'UZB', '860', '998', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('230', 'VANUATU', 'VU', 'VUT', '548', '678', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('231', 'VENEZUELA', 'VE', 'VEN', '862', '58', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('232', 'VIET NAM', 'VN', 'VNM', '704', '84', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('233', 'VIRGIN ISLANDS, BRITISH', 'VG', 'VGB', '92', '1284', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('234', 'VIRGIN ISLANDS, U.S.', 'VI', 'VIR', '850', '1340', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('235', 'WALLIS AND FUTUNA', 'WF', 'WLF', '876', '681', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('236', 'WESTERN SAHARA', 'EH', 'ESH', '732', '212', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('237', 'YEMEN', 'YE', 'YEM', '887', '967', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('238', 'ZAMBIA', 'ZM', 'ZMB', '894', '260', '1');
INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `numcode`, `phonecode`, `status`) VALUES ('239', 'ZIMBABWE', 'ZW', 'ZWE', '716', '263', '1');
